version: '3.1'
services:
    # reverse-proxy:
    #     image: nginx
    #     ports:
    #     - "8080:80"
    #     volumes:
    #     - ./my-server.conf:/etc/nginx/conf.d/default.conf
    frontend:
        image: hbd-demo-frontend:latest
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        volumes:
            - ./frontend/:/usr/src/app/
        # npm install
        container_name: hbd-demo-frontend
        ports:
            - 8080:8080
        restart: always
    backend:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        image: hbd-demo-backend:latest
        container_name: hbd-demo-backend
        volumes:
            - ./backend/:/workspace/
        environment:
            - PYTHONUNBUFFERED=1
        ports:
            - 5003:5003
        restart: always
