version: '3.1'
services:
    frontend:
        image: hbd-demo-frontend:latest
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        command: sh -c "npm install && quasar dev"
        volumes:
            - ./frontend/:/usr/src/app/
        container_name: hbd-demo-frontend
        ports:
            - 51118:51118
    backend:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        image: hbd-demo-backend:latest
        container_name: hbd-demo-backend
        volumes:
            - ./backend/:/workspace/
        command: sh -c "flask run -p 5003 --host=0.0.0.0"
        environment:
            - PYTHONUNBUFFERED=1
        ports:
            - 51119:5003
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]