http {
    server {
        listen 80;

        location / {
            proxy_pass http://frontend:51118/;
        }

        location /service2/ {
            proxy_pass http://backend:51119/;
        }

        location /service3/ {
            proxy_pass http://service3:8080/;
        }
    }
}
