FROM python:3.10

RUN mkdir -p /workspace/
WORKDIR /workspace/
ENV TZ=Europe/Rome
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN yes | apt-get install libopenblas-dev cmake
RUN CMAKE_ARGS="-DLLAMA_OPENBLAS=on" FORCE_CMAKE=1  pip install llama-cpp-python[server]
RUN mkdir /models
RUN wget -O /models/Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin https://huggingface.co/TheBloke/Wizard-Vicuna-7B-Uncensored-GGML/resolve/main/Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin
RUN pip install pydantic==1.10.11
